# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Woods Cree spellchecker"
cwd = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Woods Cree, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
cwd = "TRANSLATE: A spellchecker for Woods Cree, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.cwd"

[windows]
system_product_code = "{B5E82F32-B486-4163-B952-8D1D1E42DE38}_is1"

[package.speller]
name = "Woods Cree"
version = "0.1.0"

[package.grammar]
name = "Woods Cree"
version = "0.1.0"

[package.tts-textproc]
name = "Woods Cree"
version = "0.1.0"

[package.hyphenator]
name = "Woods Cree"
version = "0.1.0"
